apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: quarkus-compute
  name: quarkus-compute-monitor
  namespace: intel-poc
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: quarkus-compute
