apiVersion: 1

datasources:
  - name: Prometheus - Quarkus
    type: prometheus
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    access: proxy
    basicAuth: false
    withCredentials: true
    isDefault: true
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
      httpHeaderName1: "Authorization"
    secureJsonData:
    #please note you have to replace the token from 
      httpHeaderValue1: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ik14aFl1bkhJU2NEWkJpY1VKV2tzSk9jcjdTQThKYlRESG9GcXZKSkx6cGMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpbnRlbC1ncmFudWxhdGUtcG9jIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdyYWZhbmEtc2VydmljZWFjY291bnQtdG9rZW4tcnBiZnQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZ3JhZmFuYS1zZXJ2aWNlYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjQyODllOTFhLWUwNmQtNDc2Ni1iODBlLTljMTc2YTg5MjU5OCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDppbnRlbC1ncmFudWxhdGUtcG9jOmdyYWZhbmEtc2VydmljZWFjY291bnQifQ.EL_6wBPrlQ4j0E_vWMcNaRqX38aH2_IzLcM2dTE1-sb65iz1Qjs0_Je0byspgJHprqJu00u0ORuGbZpUCgJC8WwmylEQxA74iTl1V7ttJOrsv5lKYU4JN-s7m3tnCpeu6QfcJLpIBpHApsqRyyOy3z-ZvzlCSSZvIvmgUSHE38hvEFLSbMyaXT4EyE-8D5XLAgqr6_nwzfWpY9fhpN72a4LCFYEm3CAxJUA_XllMdBhO4qyBmDes33Tkom1kGc-qGkQ4s_UxaMTkBQj_ExiYEgfAWGJHQ_YuDIAgRoC7CGVP8ZQLYv77ylKGfVhQeMDgwRbbgIR5Dn1lpqsXKzcwAF_iQXVw6i6JXXLcfkuuQb2Dp8SaiAdEMBYik3Qb1hMu3Jtm1WXBLSwI5Q0GZgo5zv5MGj5n9AehilI00f2JtwrikouXzgHyv-ro5NFQO8OHY4AKCRc1sTWv9LsGrhzI2V8biYorroq3v64ZacodbaApTy8p_CsazOsyyJqXA8HKuGZsYwE7zMUgbMxoUd38sUeTh-EZfv2wPTo3tGwmm3zDoMt5E-0dy3ej5yCk8-lnOaV3caMdq6BcUXxPRjsoEAoofILdDKtoBfb1fTZSAOA70Y7zbmU3qeQcRM9vn6nvCc5E0WgriTYtr07uHv8AOu5RinamPk_zdIzEAMo4Dp4" 
    editable: true
