apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-reactive
  name: postgresql-reactive
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: postgresql-reactive
  type: ClusterIP