apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-12
  name: postgresql-12
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deployment: postgresql-12
  type: ClusterIP